services:
  - type: web
    name: fb-text-extractor
    env: docker
    region: ohio # Default US region
    plan: free # Change to starter or higher if needed
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 3000
      - key: PUPPETEER_HEADLESS
        value: new
      - key: BLOCK_HEAVY_ASSETS
        value: true
      - key: FACEBOOK_COOKIES_PATH
        value: /etc/secrets/cookies.txt
      - key: PUPPETEER_USER_AGENT
        value: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36"
    secretFiles:
      - name: cookies.txt
        value: "Copiar_aqui_el_contenido_en_Render"
