services:
  - type: web
    name: fb-text-extractor
    env: docker
    region: ohio # Default US region
    plan: free # Change to starter or higher if needed
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 3000
      - key: PUPPETEER_HEADLESS
        value: new
      - key: BLOCK_HEAVY_ASSETS
        value: true
      - key: FACEBOOK_COOKIES_PATH
        value: ./cookies.txt
    secretFiles:
      - name: cookies.txt
        value: "Copiar_aqui_el_contenido_en_Render"
